# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: helloworld.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'helloworld.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10helloworld.proto\x12\nhelloworld\"\x1e\n\x0e\x41\x64\x64WordRequest\x12\x0c\n\x04word\x18\x01 \x01(\t\"\"\n\x0f\x41\x64\x64WordResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x11\n\x0fGetWordsRequest\"!\n\x10GetWordsResponse\x12\r\n\x05words\x18\x01 \x03(\t2\x9b\x01\n\x0eWordDictionary\x12\x42\n\x07\x41\x64\x64Word\x12\x1a.helloworld.AddWordRequest\x1a\x1b.helloworld.AddWordResponse\x12\x45\n\x08GetWords\x12\x1b.helloworld.GetWordsRequest\x1a\x1c.helloworld.GetWordsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helloworld_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDWORDREQUEST']._serialized_start=32
  _globals['_ADDWORDREQUEST']._serialized_end=62
  _globals['_ADDWORDRESPONSE']._serialized_start=64
  _globals['_ADDWORDRESPONSE']._serialized_end=98
  _globals['_GETWORDSREQUEST']._serialized_start=100
  _globals['_GETWORDSREQUEST']._serialized_end=117
  _globals['_GETWORDSRESPONSE']._serialized_start=119
  _globals['_GETWORDSRESPONSE']._serialized_end=152
  _globals['_WORDDICTIONARY']._serialized_start=155
  _globals['_WORDDICTIONARY']._serialized_end=310
# @@protoc_insertion_point(module_scope)
