# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import helloworld_pb2 as helloworld__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in helloworld_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WordDictionaryStub(object):
    """Define o serviço gRPC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddWord = channel.unary_unary(
                '/helloworld.WordDictionary/AddWord',
                request_serializer=helloworld__pb2.AddWordRequest.SerializeToString,
                response_deserializer=helloworld__pb2.AddWordResponse.FromString,
                _registered_method=True)
        self.GetWords = channel.unary_unary(
                '/helloworld.WordDictionary/GetWords',
                request_serializer=helloworld__pb2.GetWordsRequest.SerializeToString,
                response_deserializer=helloworld__pb2.GetWordsResponse.FromString,
                _registered_method=True)


class WordDictionaryServicer(object):
    """Define o serviço gRPC
    """

    def AddWord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WordDictionaryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddWord': grpc.unary_unary_rpc_method_handler(
                    servicer.AddWord,
                    request_deserializer=helloworld__pb2.AddWordRequest.FromString,
                    response_serializer=helloworld__pb2.AddWordResponse.SerializeToString,
            ),
            'GetWords': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWords,
                    request_deserializer=helloworld__pb2.GetWordsRequest.FromString,
                    response_serializer=helloworld__pb2.GetWordsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'helloworld.WordDictionary', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('helloworld.WordDictionary', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WordDictionary(object):
    """Define o serviço gRPC
    """

    @staticmethod
    def AddWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helloworld.WordDictionary/AddWord',
            helloworld__pb2.AddWordRequest.SerializeToString,
            helloworld__pb2.AddWordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helloworld.WordDictionary/GetWords',
            helloworld__pb2.GetWordsRequest.SerializeToString,
            helloworld__pb2.GetWordsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
